# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cadastro_turma.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import typing
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QWidget

class SecondWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        



class Ui_CriarTurma(object):
    def setupUi(self, CriarTurma):
        CriarTurma.setObjectName("CriarTurma")
        CriarTurma.resize(1280, 740)
        CriarTurma.setMinimumSize(QtCore.QSize(1280, 740))
        self.centralwidget = QtWidgets.QWidget(CriarTurma)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_botton = QtWidgets.QFrame(self.centralwidget)
        self.top_botton.setMaximumSize(QtCore.QSize(16777215, 35))
        self.top_botton.setStyleSheet("background-color: rgb(51, 51, 51);")
        self.top_botton.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_botton.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_botton.setObjectName("top_botton")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_botton)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addWidget(self.top_botton)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setStyleSheet("\n"
"background-color: rgb(51, 51, 51);")
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Criar_turma = QtWidgets.QFrame(self.content)
        self.Criar_turma.setMinimumSize(QtCore.QSize(1280, 566))
        self.Criar_turma.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Criar_turma.setStyleSheet("background-color: rgb(238, 238, 238);")
        self.Criar_turma.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Criar_turma.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Criar_turma.setObjectName("Criar_turma")
        self.label = QtWidgets.QLabel(self.Criar_turma)
        self.label.setGeometry(QtCore.QRect(440, 250, 366, 35))
        self.label.setMaximumSize(QtCore.QSize(400, 320))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_CriarTurma = QtWidgets.QPushButton(self.Criar_turma)
        self.pushButton_CriarTurma.setGeometry(QtCore.QRect(500, 290, 201, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_CriarTurma.sizePolicy().hasHeightForWidth())
        self.pushButton_CriarTurma.setSizePolicy(sizePolicy)
        self.pushButton_CriarTurma.setMaximumSize(QtCore.QSize(390, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_CriarTurma.setFont(font)
        self.pushButton_CriarTurma.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_CriarTurma.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(51, 51, 51);\n"
"    border: 2px solid rgb(60,60,60);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(60,60,60);\n"
"    border: 2px solid rgb(70,70,70);\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120,120,120);\n"
"    border: 2px solid rgb(90,90,90);\n"
"}\n"
"")
        self.pushButton_CriarTurma.setObjectName("pushButton_CriarTurma")
        self.horizontalLayout.addWidget(self.Criar_turma)
        self.verticalLayout.addWidget(self.content)
        self.botton = QtWidgets.QFrame(self.centralwidget)
        self.botton.setMaximumSize(QtCore.QSize(16777215, 35))
        self.botton.setStyleSheet("background-color: rgb(238, 238, 238);")
        self.botton.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.botton.setFrameShadow(QtWidgets.QFrame.Raised)
        self.botton.setObjectName("botton")
        self.verticalLayout.addWidget(self.botton)
        CriarTurma.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CriarTurma)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        CriarTurma.setMenuBar(self.menubar)

        self.retranslateUi(CriarTurma)
        QtCore.QMetaObject.connectSlotsByName(CriarTurma)

    def retranslateUi(self, CriarTurma):
        _translate = QtCore.QCoreApplication.translate
        CriarTurma.setWindowTitle(_translate("CriarTurma", "Login"))
        self.label.setText(_translate("CriarTurma", "Adicione a turma para começar"))
        self.pushButton_CriarTurma.setText(_translate("CriarTurma", "Criar turma"))
import teste.files


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CriarTurma = QtWidgets.QMainWindow()
    ui = Ui_CriarTurma()
    ui.setupUi(CriarTurma)
    CriarTurma.show()
    sys.exit(app.exec_())
