# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Criar_Aluno.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CriarTurma(object):
    def setupUi(self, CriarTurma):
        CriarTurma.setObjectName("CriarTurma")
        CriarTurma.resize(1280, 740)
        CriarTurma.setMinimumSize(QtCore.QSize(1280, 740))
        self.centralwidget = QtWidgets.QWidget(CriarTurma)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_botton = QtWidgets.QFrame(self.centralwidget)
        self.top_botton.setMaximumSize(QtCore.QSize(16777215, 35))
        self.top_botton.setStyleSheet("background-color: rgb(51, 51, 51);")
        self.top_botton.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_botton.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_botton.setObjectName("top_botton")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_botton)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addWidget(self.top_botton)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setStyleSheet("\n"
"background-color: rgb(51, 51, 51);")
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Criar_turma = QtWidgets.QFrame(self.content)
        self.Criar_turma.setMinimumSize(QtCore.QSize(1280, 566))
        self.Criar_turma.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Criar_turma.setStyleSheet("\n"
"background-color: rgb(217, 217, 217);")
        self.Criar_turma.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Criar_turma.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Criar_turma.setObjectName("Criar_turma")
        self.frame = QtWidgets.QFrame(self.Criar_turma)
        self.frame.setGeometry(QtCore.QRect(310, 80, 553, 484))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(40, 20, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_user = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_user.setGeometry(QtCore.QRect(40, 130, 461, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_user.setFont(font)
        self.lineEdit_user.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_user.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45,45,45,45)\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30,30,30,30);\n"
"    rgba(100, 100, 100, 100)\n"
"\n"
"}\n"
"\n"
"")
        self.lineEdit_user.setText("")
        self.lineEdit_user.setPlaceholderText("")
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.pushButton_salvar = QtWidgets.QPushButton(self.frame)
        self.pushButton_salvar.setGeometry(QtCore.QRect(216, 440, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_salvar.setFont(font)
        self.pushButton_salvar.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(51, 51, 51);\n"
"    border: 2px solid rgb(60,60,60);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(60,60,60);\n"
"    border: 2px solid rgb(70,70,70);\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120,120,120);\n"
"    border: 2px solid rgb(90,90,90);\n"
"}\n"
"")
        self.pushButton_salvar.setObjectName("pushButton_salvar")
        self.lineEdit_cod_disciplina = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_cod_disciplina.setGeometry(QtCore.QRect(40, 210, 461, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_cod_disciplina.setFont(font)
        self.lineEdit_cod_disciplina.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_cod_disciplina.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45,45,45,45)\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30,30,30,30);\n"
"    rgba(100, 100, 100, 100)\n"
"\n"
"}\n"
"\n"
"")
        self.lineEdit_cod_disciplina.setText("")
        self.lineEdit_cod_disciplina.setPlaceholderText("")
        self.lineEdit_cod_disciplina.setObjectName("lineEdit_cod_disciplina")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 103, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(40, 190, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(40, 60, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(40, 340, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_caminho_foto = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_caminho_foto.setGeometry(QtCore.QRect(40, 370, 461, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_caminho_foto.setFont(font)
        self.lineEdit_caminho_foto.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_caminho_foto.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45,45,45,45)\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30,30,30,30);\n"
"    rgba(100, 100, 100, 100)\n"
"\n"
"}\n"
"\n"
"")
        self.lineEdit_caminho_foto.setText("")
        self.lineEdit_caminho_foto.setPlaceholderText("")
        self.lineEdit_caminho_foto.setObjectName("lineEdit_caminho_foto")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(40, 270, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_matricula = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_matricula.setGeometry(QtCore.QRect(40, 290, 461, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_matricula.setFont(font)
        self.lineEdit_matricula.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_matricula.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45,45,45,45)\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30,30,30,30);\n"
"    rgba(100, 100, 100, 100)\n"
"\n"
"}\n"
"\n"
"")
        self.lineEdit_matricula.setText("")
        self.lineEdit_matricula.setPlaceholderText("")
        self.lineEdit_matricula.setObjectName("lineEdit_matricula")
        self.horizontalLayout.addWidget(self.Criar_turma)
        self.verticalLayout.addWidget(self.content)
        self.botton = QtWidgets.QFrame(self.centralwidget)
        self.botton.setMaximumSize(QtCore.QSize(16777215, 35))
        self.botton.setStyleSheet("\n"
"background-color: rgb(217, 217, 217);")
        self.botton.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.botton.setFrameShadow(QtWidgets.QFrame.Raised)
        self.botton.setObjectName("botton")
        self.verticalLayout.addWidget(self.botton)
        CriarTurma.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CriarTurma)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        CriarTurma.setMenuBar(self.menubar)

        self.retranslateUi(CriarTurma)
        QtCore.QMetaObject.connectSlotsByName(CriarTurma)

    def retranslateUi(self, CriarTurma):
        _translate = QtCore.QCoreApplication.translate
        CriarTurma.setWindowTitle(_translate("CriarTurma", "Login"))
        self.label.setText(_translate("CriarTurma", "Disciplina A"))
        self.pushButton_salvar.setText(_translate("CriarTurma", "Salvar"))
        self.label_2.setText(_translate("CriarTurma", "Nome do Aluno"))
        self.label_3.setText(_translate("CriarTurma", "Código da Disciplina"))
        self.label_4.setText(_translate("CriarTurma", "Adicionar Alunos"))
        self.label_5.setText(_translate("CriarTurma", "Foto"))
        self.label_6.setText(_translate("CriarTurma", "Matrícula"))
import file_rc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CriarTurma = QtWidgets.QMainWindow()
    ui = Ui_CriarTurma()
    ui.setupUi(CriarTurma)
    CriarTurma.show()
    sys.exit(app.exec_())
