# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CriarTurma(object):
    def setupUi(self, CriarTurma):
        CriarTurma.setObjectName("CriarTurma")
        CriarTurma.resize(1280, 740)
        CriarTurma.setMinimumSize(QtCore.QSize(1280, 740))
        self.centralwidget = QtWidgets.QWidget(CriarTurma)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_botton = QtWidgets.QFrame(self.centralwidget)
        self.top_botton.setMaximumSize(QtCore.QSize(16777215, 35))
        self.top_botton.setStyleSheet("background-color: rgb(51, 51, 51);")
        self.top_botton.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_botton.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_botton.setObjectName("top_botton")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_botton)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addWidget(self.top_botton)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setStyleSheet("\n"
"background-color: rgb(51, 51, 51);")
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Criar_turma = QtWidgets.QFrame(self.content)
        self.Criar_turma.setMinimumSize(QtCore.QSize(1280, 566))
        self.Criar_turma.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Criar_turma.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.Criar_turma.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Criar_turma.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Criar_turma.setObjectName("Criar_turma")
        self.frame = QtWidgets.QFrame(self.Criar_turma)
        self.frame.setGeometry(QtCore.QRect(469, 210, 341, 281))
        self.frame.setStyleSheet("\n"
"background-color: rgb(238, 238, 238);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_nome_disciplina = QtWidgets.QLabel(self.frame)
        self.label_nome_disciplina.setGeometry(QtCore.QRect(100, 40, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_nome_disciplina.setFont(font)
        self.label_nome_disciplina.setObjectName("label_nome_disciplina")
        self.pushButton_adicionar_aluno = QtWidgets.QPushButton(self.frame)
        self.pushButton_adicionar_aluno.setGeometry(QtCore.QRect(110, 110, 111, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_adicionar_aluno.setFont(font)
        self.pushButton_adicionar_aluno.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(51, 51, 51);\n"
"    border: 2px solid rgb(60,60,60);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(60,60,60);\n"
"    border: 2px solid rgb(70,70,70);\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120,120,120);\n"
"    border: 2px solid rgb(90,90,90);\n"
"}\n"
"")
        self.pushButton_adicionar_aluno.setObjectName("pushButton_adicionar_aluno")
        self.pushButton_registrar_aula = QtWidgets.QPushButton(self.frame)
        self.pushButton_registrar_aula.setGeometry(QtCore.QRect(110, 170, 111, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_registrar_aula.setFont(font)
        self.pushButton_registrar_aula.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(51, 51, 51);\n"
"    border: 2px solid rgb(60,60,60);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(60,60,60);\n"
"    border: 2px solid rgb(70,70,70);\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120,120,120);\n"
"    border: 2px solid rgb(90,90,90);\n"
"}\n"
"")
        self.pushButton_registrar_aula.setObjectName("pushButton_registrar_aula")
        self.horizontalLayout.addWidget(self.Criar_turma)
        self.verticalLayout.addWidget(self.content)
        self.botton = QtWidgets.QFrame(self.centralwidget)
        self.botton.setMaximumSize(QtCore.QSize(16777215, 35))
        self.botton.setStyleSheet("background-color: rgb(217,217,217);")
        self.botton.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.botton.setFrameShadow(QtWidgets.QFrame.Raised)
        self.botton.setObjectName("botton")
        self.verticalLayout.addWidget(self.botton)
        CriarTurma.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CriarTurma)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        CriarTurma.setMenuBar(self.menubar)

        self.retranslateUi(CriarTurma)
        QtCore.QMetaObject.connectSlotsByName(CriarTurma)

    def retranslateUi(self, CriarTurma):
        _translate = QtCore.QCoreApplication.translate
        CriarTurma.setWindowTitle(_translate("CriarTurma", "Login"))
        self.label_nome_disciplina.setText(_translate("CriarTurma", "Disciplina A"))
        self.pushButton_adicionar_aluno.setText(_translate("CriarTurma", "Adicionar aluno"))
        self.pushButton_registrar_aula.setText(_translate("CriarTurma", "Registrar aula"))
import file_rc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CriarTurma = QtWidgets.QMainWindow()
    ui = Ui_CriarTurma()
    ui.setupUi(CriarTurma)
    CriarTurma.show()
    sys.exit(app.exec_())
